/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 oculus_quest_vr_headset.glb
Author: BlackCube (https://sketchfab.com/blackcube4)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/oculus-quest-vr-headset-0d6c1d6aa3f747a5b35f8105ed585418
Title: Oculus Quest VR Headset
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export function Model(props) {
  const myMesh = React.useRef();

  useFrame(({ clock }) => {
    const a = clock.getElapsedTime();
    myMesh.current.rotation.y = a;
  });

  const { nodes, materials } = useGLTF('/oculus_quest_vr_headset.glb')
  return (
    <group {...props}  dispose={null} ref={myMesh}  >
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.4} >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0.3, -1.41]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Object_4.geometry} material={materials.Quest_Front} />
            <mesh geometry={nodes.Object_5.geometry} material={materials.Quest_Stoff} />
            <mesh geometry={nodes.Object_6.geometry} material={materials.Quest_Stecker} />
            <mesh geometry={nodes.Object_7.geometry} material={materials.Quest_Samt} />
            <mesh geometry={nodes.Object_8.geometry} material={materials.Quest_Foam} />
            <mesh geometry={nodes.Object_9.geometry} material={materials.Quest_Headstrap} />
            <mesh geometry={nodes.Object_10.geometry} material={materials.Quest_Plastik} />
            <mesh geometry={nodes.Object_11.geometry} material={materials.Quest_Kamera_Linsen} />
            <mesh geometry={nodes.Object_12.geometry} material={materials.Quest_Kamera} />
            <mesh geometry={nodes.Object_13.geometry} material={materials.Quest_Samt_2} />
            <mesh geometry={nodes.Object_14.geometry} material={materials.Quest_Screen} />
            <mesh geometry={nodes.Object_15.geometry} material={materials.Quest_Gummi_Linse} />
            <mesh geometry={nodes.Object_16.geometry} material={materials.Quest_Lautstrketaste} />
            <mesh geometry={nodes.Object_17.geometry} material={materials.Quest_Linsen} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/oculus_quest_vr_headset.glb');